
export const data = [
    {
        'id': 'react',
        'titulo': 'Learn React in 20 minutes',
        'canal':'Alexis Aguirre',
        'vistas': '2.5M',
        'fecha': 'hace 4 dias',
        'imagenCanal':'alexiss',
        'descripcion': 'Empezaremos este gran viaje desde lo más básico para personas que estén iniciando su proceso y se les pueda facilitar su avance a niveles superiores, luego pasaremos al nivel intermedio que es una parte bastante importante, debido que es una de las más utilizadas actualmente por las empresas y una alta demanda en sus funciones, y finalmente llegaremos al nivel avanzado brindando herramientas maravillosas con casos prácticos y reales que serán de gran utilidad en la vida profesional.',
        'fecha2': '19 Octubre 2020',
        'like':'555',
        'dislike': '1',
        'alumnos': '150.000 alumnos'
    },
    {
        'id': 'excel',
        'titulo': 'Excel Completo - Desde Principiante a Avanzado',
        'canal':'Miguel Marabi',
        'vistas': '5.2M',
        'fecha': 'hace 3 meses',
        'imagenCanal':'miguel',
        'descripcion': 'El Curso Completo de Microsoft Excel, está pensado analíticamente para brindarle al estudiante todos los conocimientos necesarios para lograr ser un experto en esta poderosa plataforma.',
        'fecha2': '20 Enero 2021',
        'like':'556',
        'dislike': '125',
        'alumnos': '150 alumnos'
    },
    {
        'id': 'html',
        'titulo': 'Aprende Javascript ES9, HTML, CSS3 y NodeJS desde cero',
        'canal':'Nicolas Schurman',
        'vistas': '35.2M',
        'fecha': 'hace 2 años',
        'imagenCanal':'nicolas',
        'descripcion': 'Acá aprenderás a programar desde cero con javascript, pensando que no tienes ningún conocimiento sobre programación desde antes.',
        'fecha2': '7 Julio 2020',
        'like':'15200',
        'dislike': '2',
        'alumnos': '24.584 alumnos'
    },
    {
        'id': 'aws',
        'titulo': 'Amazon AWS. Curso básico de Amazon AWS. Aprende desde cero',
        'canal':'Redait Media',
        'vistas': '35k',
        'fecha': 'hace 4 semanas',
        'imagenCanal':'redait',
        'descripcion': 'Aprenderás a manejar Amazon AWS, el servicio de computación en la nube de Amazon. El más utilizado del mercado.',
        'fecha2': '15 Noviembre 2020',
        'like':'325',
        'dislike': '15',
        'alumnos': '10.000 alumnos'
    },
    {
        'id': 'docker',
        'titulo': 'Aprende Docker desde Cero a Swarm y Kubernetes',
        'canal':'Apasoft Training',
        'vistas': '165k',
        'fecha': 'hace 3 meses',
        'imagenCanal':'apa',
        'descripcion': 'En este curso aprenderás a trabajar con la interesante infraestructura de contenedores Docker. Esta tecnología te permitirá mejorar en tus carrera labora y profesional, ya que es una de las más demandadas en estos momentos, sobre todo porque es  usada para Devops y Desarrolladores en entornos de microservicios y similares',
        'fecha2': '25 ene. 2020',
        'like':'3256',
        'dislike': '25',
        'alumnos': '150.000 alumnos'
    },
    {
        'id': 'js',
        'titulo': 'Curso de JavaScript Completo - Aula Demonstrativa',
        'canal':'DevMedia',
        'vistas': '15,744',
        'fecha': 'hace 3 años',
        'imagenCanal':'dev',
        'descripcion': 'Em nosso curso de Javascript veremos todos os conceitos dessa linguagem de programação desde os conceitos básicos até os mais avançados, para que o aluno tenho uma formação completa de Javascript',
        'fecha2': '3 jul. 2017',
        'like':'104',
        'dislike': '5',
        'alumnos': '114.000 alumnos'
    },
    {
        'id': 'angular',
        'titulo': 'Angular 6 Curso Practico',
        'canal':'Fazt',
        'vistas': '327,000',
        'fecha': 'hace 2 años',
        'imagenCanal':'fazt',
        'descripcion': 'Aprende a desarrollar aplicaciones web frontend usando el framework de frontend Angular. aprenderemos a instalar nuestro entorno de desarrollo, crear nuestro primero proyecto y aprender los conceptos basicos como el uso de angular-cli, la creación de componentes, directivas, servicios, el uso de typescript y más.',
        'fecha2': '10 jul. 2018',
        'like':'7207',
        'dislike': '109',
        'alumnos': '327.000 alumnos'
    },
    {
        'id': 'vue',
        'titulo': 'Curso Vue.js en Español',
        'canal':'Alonso Enriquez',
        'vistas': '21,000',
        'fecha': 'hace 1 año',
        'imagenCanal':'alonso',
        'descripcion': '¿Buscas un curso de Vue.js 2 en español? Aquí tienes una formación online que te permitirá conocer todas las posibilidades de este framework progresivo. Aprende a utilizar este interesante framework para la programación backend con este completo curso de Vue.js en español, y que podrás hacer en tu tiempo libre.',
        'fecha2': '12 jul. 2020',
        'like':'620',
        'dislike': '51',
        'alumnos': '180.000 alumnos'
    },
    {
        'id': 'fluter',
        'titulo': 'Curso Introducción a Flutter',
        'canal':'G Coding Academy',
        'vistas': '20,850',
        'fecha': 'hace 1 año',
        'imagenCanal':'gteam',
        'descripcion': 'En este curso, aprenderás a desarrollar aplicaciones móviles esenciales utilizando el SDK de Flutter, framework de plataformas cruzadas desarrollado por Google.',
        'fecha2': '13 jul. 2020',
        'like':'407',
        'dislike': '5',
        'alumnos': '16.900 alumnos'
    },
    {
        'id': 'java',
        'titulo': 'Curso de Java Básico',
        'canal':'Codigo Facilito',
        'vistas': '76,283',
        'fecha': 'hace 8 años',
        'imagenCanal':'facil',
        'descripcion': 'Información de Jorge, tutor del Curso de Java en CódigoFacilito:   Twitter de Jorge: ‪http://twitter.com/jorge_vgut‬​      Sitio de Jorge: ‪http://codigoprogramacion.com/‬',
        'fecha2': '18 feb. 2012',
        'like':'914',
        'dislike': '12',
        'alumnos': '650.000 alumnos'
    },
    {
        'id': 'python',
        'titulo': 'Curso Python',
        'canal':'PildorasInformaticas',
        'vistas': '1,584,331',
        'fecha': 'hace 3 años',
        'imagenCanal':'pill',
        'descripcion': 'Comenzamos con esta presentación el curso de Python. En este vídeo se ven los temas que se tratarán a lo largo del curso. Espero que os guste.‬',
        'fecha2': '24 ene. 2017',
        'like':'23,673',
        'dislike': '142',
        'alumnos': '592.000 alumnos'
    },
    {
        'id': 'sql',
        'titulo': 'Curso SQL Basico',
        'canal':'PildorasInformaticas',
        'vistas': '580,736',
        'fecha': 'hace 5 años',
        'imagenCanal':'pill',
        'descripcion': 'Comenzamos con esta entrega un nuevo curso de SQL. Este curso es necesario para aquellos que manejen tecnologías que accedan a BBDD remotas.‬',
        'fecha2': '16 jul. 2015',
        'like':'6723',
        'dislike': '52',
        'alumnos': '592.000 alumnos'
    },
    {
        'id': 'php',
        'titulo': 'Curso de PHP básico y desde CERO!',
        'canal':'Bluuweb !',
        'vistas': '59,068',
        'fecha': 'hace 3 años',
        'imagenCanal':'bluu',
        'descripcion': 'Bienvenidos a la primera entrega del curso de PHP para principiantes, aquí comenzaremos desde cero y para principiantes.',
        'fecha2': '13 sep. 2017',
        'like':'1019',
        'dislike': '3',
        'alumnos': '142.000 alumnos'
    },
    {
        'id': 'io',
        'titulo': ' Curso de Ionic Framework',
        'canal':'Eduardo Ibarra',
        'vistas': '89,380',
        'fecha': 'hace 4 años',
        'imagenCanal':'edu',
        'descripcion': 'Aprende a crear aplicaciones para Android y iOS de una manera muy sencilla usando HTML5, Javascript y CSS con Ionic.‬',
        'fecha2': '24 mar. 2016',
        'like':'1324',
        'dislike': '13',
        'alumnos': '8570 alumnos'
    },
    {
        'id': 'css',
        'titulo': 'Curso de CSS AVANZADO 🔥',
        'canal':'yacklyon',
        'vistas': '4075',
        'fecha': 'hace 1 años',
        'imagenCanal':'css2',
        'descripcion': 'CSS: Es el estilo que le aplicamos a cada uno de los elementos creados previamente en el HTML. Bienvenido al curso de css avanzado!!',
        'fecha2': 'Se estrenó el 12 oct. 2020',
        'like':'156',
        'dislike': '0',
        'alumnos': '30.600 alumnos'
    },
    {
        'id': 'laravel',
        'titulo': 'Curso Laravel 5 desde cero',
        'canal':'Bluuweb !',
        'vistas': '18,043',
        'fecha': 'hace 2 años',
        'imagenCanal':'bluu',
        'descripcion': 'En esta sección veremos algo sumamente útil con Laravel 5.8 y es la autenticación, un método simple y rápido para realizar tus propios proyectos con registro de usuario y accesos restringidos.‬',
        'fecha2': '18 jun. 2019',
        'like':'442',
        'dislike': '5',
        'alumnos': '142.000 alumnos'
    },

    
    
    
    
]